### PR TITLE
fix(combobox): Force sync on bind

### PR DESCRIPTION
**Pull request by davismj**
Fixes an issue with the combo box where bindings refresh after the element is attached. Previously, my element would not properly bind to the value.

### CODE REVIEW

**Comment by JeroenVinke** [comment]
Before I can merge this, i'd like to reproduce the issue. Can you provide more info?

**Comment by davismj** [comment]
Sure. Basically, I had a template bound to a particular object. Within the template was a combobox bound to a property on the object. As I switched which object was bound to the template, the combobox did not update with the value of the property on the new object. 

This fix makes sure that on every bind, the value displayed is synced to the value of the object.

**Comment by JeroenVinke** [comment]
That makes sense. Perhaps we can go one step further and ensure that other properties (and other controls) get updated as well (e.g. `k-checked` for the switch control). I'll see if I can put something together

**Comment by adriatic** [comment]
What a great improvement in a two quick steps. Thanks @davismj, I wish there would be more contributions like yours 😄

**Pull request closed without merging**
